#!/bin/sh

#export JBOSS_CONTAINER_UTIL_LOGGING_MODULE=/opt/jboss/container/util/logging
#export JBOSS_CONTAINER_MAVEN_S2I_MODULE=/opt/jboss/container/maven/s2i
#export JBOSS_CONTAINER_JAVA_S2I_MODULE=/opt/jboss/container/java/s2i
#set -e
#source "${JBOSS_CONTAINER_UTIL_LOGGING_MODULE}/logging.sh"
#source "${JBOSS_CONTAINER_MAVEN_S2I_MODULE}/maven-s2i"
# include our s2i_core_*() overrides/extensions
#source "${JBOSS_CONTAINER_JAVA_S2I_MODULE}/s2i-core-hooks"
# inject our overridden maven_s2i_*() functions
#source "${JBOSS_CONTAINER_JAVA_S2I_MODULE}/maven-s2i-overrides"
# invoke the build
#maven_s2i_build

echo "Before assembling"

/usr/libexec/s2i/assemble
rc=$?

if [ $rc -eq 0 ]; then
    echo "After successful assembling"
else
    echo "After failed assembling"
fi

exit $rc
