#!/bin/sh

#export JBOSS_CONTAINER_UTIL_LOGGING_MODULE=/opt/jboss/container/util/logging
#export JBOSS_CONTAINER_MAVEN_S2I_MODULE=/opt/jboss/container/maven/s2i
#export JBOSS_CONTAINER_JAVA_S2I_MODULE=/opt/jboss/container/java/s2i
#set -e
#source "${JBOSS_CONTAINER_UTIL_LOGGING_MODULE}/logging.sh"
#source "${JBOSS_CONTAINER_MAVEN_S2I_MODULE}/maven-s2i"
# include our s2i_core_*() overrides/extensions
#source "${JBOSS_CONTAINER_JAVA_S2I_MODULE}/s2i-core-hooks"
# inject our overridden maven_s2i_*() functions
#source "${JBOSS_CONTAINER_JAVA_S2I_MODULE}/maven-s2i-overrides"
# invoke the build
#maven_s2i_build

#!/bin/bash

# restore build artifacts
if [ "$(ls /tmp/artifacts/ 2>/dev/null)" ]; then
    mv /tmp/artifacts/* $HOME/.
fi

# move the application source
#mv /tmp/s2i/src $HOME/src

# build application artifacts
pushd ${HOME}
#make all

# install the artifacts
#make install
popd
